name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install root
        run: npm install
      - name: Install API deps
        run: npm install
        working-directory: api
      - name: Install Web deps
        run: npm install
        working-directory: web
      - name: Test API
        run: npm test
        working-directory: api
      - name: Test Web
        run: npm test
        working-directory: web

